<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HomelabHub.Discord</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomelabHub.Abstractions\HomelabHub.Abstractions.csproj" />
    <ProjectReference Include="..\HomelabHub.Core\HomelabHub.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net.WebSocket" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HomelabHub.Discord.Tests" />
  </ItemGroup>

</Project>
